
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('Primitive variables are stored on Stack.');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('What is the size of float variable?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('What is the default value of float variable?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('Which of the following is true about String?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('What is Abstraction?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('What is an applet?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('Dynamic binding uses which information for binding?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('What is Serialization?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('Can try statements be nested?');
INSERT INTO `quizdb`.`question` (`questionText`) VALUES ('Which of the following is a thread safe?');

INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('True', '1');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('False', '1');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('8 bit', '2');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('16 bit', '2');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('32 bit', '2');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('64 bit', '2');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('0.0d', '3');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('0.0f', '3');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('0', '3');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('not defind', '3');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('String is mutable', '4');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('String is immutable', '4');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('String is  a data type', '4');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('None of the above', '4');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Abstraction is a thechnique to define different methods of same type', '5');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Abstraction is the ability of an object to make onmany forms', '5');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('It refers to the ability to make a class abstract in OOP', '5');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('None of the above', '5');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('An applet is a Java program that runs in a  Web browser', '6');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Applet is a standalone java program', '6');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Applet is a tool', '6');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Applet is a run time environment', '6');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('type', '7');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('object', '7');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('both of the above', '7');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('None of the above', '7');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Serialization is the process of writing the state of an object to another object', '8');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Serialization is the process of writing the state of an object to a byte stream', '8');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Both of the above', '8');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('None of the above', '8');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('True', '9');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('False', '9');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('StringBuilder', '0');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('StringBuffer', '0');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('Both of the above', '0');
INSERT INTO `quizdb`.`answer` (`text`, `question_id`) VALUES ('None of the above', '0');

UPDATE `quizdb`.`question` SET `answer_id`='1' WHERE `id`='1';
UPDATE `quizdb`.`question` SET `answer_id`='5' WHERE `id`='2';
UPDATE `quizdb`.`question` SET `answer_id`='8' WHERE `id`='3';
UPDATE `quizdb`.`question` SET `answer_id`='11' WHERE `id`='4';
UPDATE `quizdb`.`question` SET `answer_id`='17' WHERE `id`='5';
UPDATE `quizdb`.`question` SET `answer_id`='19' WHERE `id`='6';
UPDATE `quizdb`.`question` SET `answer_id`='24' WHERE `id`='7';
UPDATE `quizdb`.`question` SET `answer_id`='28' WHERE `id`='8';
UPDATE `quizdb`.`question` SET `answer_id`='31' WHERE `id`='9';
UPDATE `quizdb`.`question` SET `answer_id`='34' WHERE `id`='10';

